# Generated by Django 3.1.7 on 2021-03-19 15:05

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
