# Generated by Django 3.1.7 on 2021-03-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
