# Generated by Django 3.1.7 on 2021-03-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20210319_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
    ]
