# Generated by Django 3.1.7 on 2021-03-18 07:14

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210318_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
