# Generated by Django 3.1.7 on 2021-03-18 07:14

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_appointment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=254),
        ),
    ]
