# Generated by Django 3.1.7 on 2021-03-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20210318_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='spciality',
            new_name='speciality',
        ),
    ]
