# Generated by Django 3.1.7 on 2021-03-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20210318_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(blank=True, default='Not Contacted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.status'),
        ),
    ]
