# Generated by Django 3.1.7 on 2021-03-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20210318_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
