# Generated by Django 3.1.7 on 2021-03-19 11:07

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20210319_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.department'),
        ),
    ]
